export class UsersDB {
  public static users = [
    {
      _id: "5a9ae2106518248b68251fdf",
      fullName: "Hasaneen Nabil",
      username: "hasaneenDev",
      roles: "Admin",
      isActive: true,
      isLoggedIn: false,
    },
    {
      _id: "5a9ae2106518248b68251fdw",
      fullName: "Mahmood Shakir",
      username: "mahmood",
      roles: "Monitor",
      isActive: false,
      isLoggedIn: false,
    },
    {
      _id: "5a9ae2106518248b68251fdv",
      fullName: "Mustafa Hassan",
      username: "mustafaBj",
      roles: "Admin",
      isActive: true,
      isLoggedIn: true,
    },
    {
      _id: "5a9ae2106518248b68251fdj",
      fullName: "Ahmed Jassem",
      username: "ahmed",
      roles: "Statistics",
      isActive: true,
      isLoggedIn: true,
    },
    {
      _id: "5a9ae2106518248b68251fdy",
      fullName: "Ramon",
      username: "ramon",
      roles: "Admin",
      isActive: true,
      isLoggedIn: true,
    },
    {
      _id: "5a9ae2106518248b68251fdl",
      fullName: "Hussam",
      username: "hussam",
      roles: "Management",
      isActive: false,
      isLoggedIn: false,
    },
    {
      _id: "5a9ae2106518248b68251fdl",
      fullName: "Hussam",
      username: "hussam",
      roles: "Management",
      isActive: true,
      isLoggedIn: false,
    },
    {
      _id: "5a9ae2106518248b68251fdl",
      fullName: "Hussam",
      username: "hussam",
      roles: "Management",
      isActive: true,
      isLoggedIn: false,
    },
    {
      _id: "5a9ae2106518248b68251fdl",
      fullName: "Hussam",
      username: "hussam",
      roles: "Management",
      isActive: false,
      isLoggedIn: false,
    },
    {
      _id: "5a9ae2106518248b68251fdl",
      fullName: "Hussam",
      username: "hussam",
      roles: "Management",
      isActive: false,
      isLoggedIn: true,
    },
  ];
}
